// SpeedQuiz — Monthly Questions
// Auto-generated by excel_to_questions.html
// Do not edit by hand — regenerate from your Excel template instead.
//
// Columns by type:
//   multiple_choice : options (up to 6), answer
//   letters         : answer (letter), display_answer (full word)
//   numbers         : answer (integer)
//   sequence        : items (up to 6, shown shuffled), answer (correct order array)
//   wordsnake       : answer (word or phrase, max 20 letters — spaces don't count)
//   tapspot         : target (JSON array of {x,y} points from the Shape Picker
//                     tool, min 3), requires an image in the media column
//   optional media  : column P is the file/URL; column Q can specify image, video, or audio.
//                     If Q is blank, the type is inferred from its extension.

window.QUIZ_QUESTIONS = {
  "2026-07-19": [
    {
      "type": "wordsnake",
      "question": "Word Snake: Name the Artist…",
      "answer": "Shakira",
      "media": {
        "type": "video",
        "url": "media\\sh.mp4"
      }
    },
    {
      "type": "sequence",
      "question": "Put these six chart‑hit songs by Madonna in order of their original release…",
      "items": [
        "Holiday",
        "Like a Virgin",
        "Material Girl",
        "Papa Don’t Preach",
        "Like a Prayer",
        "Vogue"
      ],
      "answer": [
        "Holiday",
        "Like a Virgin",
        "Material Girl",
        "Papa Don’t Preach",
        "Like a Prayer",
        "Vogue"
      ]
    },
    {
      "type": "letters",
      "question": "Name the Artist from the Album Cover…",
      "answer": "W",
      "display_answer": "The White Stripes (Elephant)",
      "media": {
        "type": "image",
        "url": "media\\ws.jpg"
      }
    },
    {
      "type": "letters",
      "question": "Name the Track…",
      "answer": "W",
      "display_answer": "Watching The Detectives (Elvis Costello)",
      "media": {
        "type": "audio",
        "url": "media\\ec.mp3"
      }
    },
    {
      "type": "sequence",
      "question": "Put the following in Order to make a Track followed by the Artist…",
      "items": [
        "WON",
        "DER",
        "WAL",
        "L O",
        "ASI",
        "S"
      ],
      "answer": [
        "WON",
        "DER",
        "WAL",
        "L O",
        "ASI",
        "S"
      ]
    },
    {
      "type": "letters",
      "question": "Name the Track from the opening lyrics…",
      "answer": "S",
      "display_answer": "Sympathy for the Devil (The Rolling Stones)",
      "media": {
        "type": "video",
        "url": "media\\rs.mp4"
      }
    },
    {
      "type": "letters",
      "question": "One Hit Wonder: Name the Artist…",
      "answer": "B",
      "display_answer": "Baz Lurman (Everyone's Free To Wear Sunscreen)",
      "media": {
        "type": "video",
        "url": "media\\bl.mp4"
      }
    },
    {
      "type": "multiple_choice",
      "question": "The song “All Star” by Smash Mouth was the theme song for which 1999 movie?",
      "options": [
        "Shrek",
        "Shrek 2",
        "Digimon: The Movie",
        "Rat Race",
        "Toy Story",
        "Mystery Men"
      ],
      "answer": "Mystery Men"
    },
    {
      "type": "multiple_choice",
      "question": "Name the Artist who sang the Original…",
      "options": [
        "Tailor Swift",
        "Tayler Swift",
        "Taylore Swift",
        "Tayor Swift",
        "Taylor Swift",
        "Tayla Swift"
      ],
      "answer": "Taylor Swift",
      "media": {
        "type": "video",
        "url": "media\\sw.mp4"
      }
    },
    {
      "type": "numbers",
      "question": "In what year did Wham! reach Number One in the UK with Last Christmas?",
      "answer": 2021
    }
  ],
  "2026-07-18": [
    {
      "type": "wordsnake",
      "question": "Word Snake: Name the Artist…",
      "answer": "Lana Del Ray",
      "media": {
        "type": "video",
        "url": "media\\lr.mp4"
      }
    },
    {
      "type": "sequence",
      "question": "Put these six chart‑hit songs by Ed Sheeran in order of their original release…",
      "items": [
        "The A Team",
        "Sing",
        "Thinking Out Loud",
        "Photograph",
        "Shape of You",
        "Perfect"
      ],
      "answer": [
        "The A Team",
        "Sing",
        "Thinking Out Loud",
        "Photograph",
        "Shape of You",
        "Perfect"
      ]
    },
    {
      "type": "letters",
      "question": "Name the Artist from the Album Cover…",
      "answer": "D",
      "display_answer": "David Bowie (Black Star)",
      "media": {
        "type": "image",
        "url": "media\\db.png"
      }
    },
    {
      "type": "letters",
      "question": "Name the Track…",
      "answer": "M",
      "display_answer": "My Sharona (The Knack)",
      "media": {
        "type": "audio",
        "url": "media\\tk.mp3"
      }
    },
    {
      "type": "sequence",
      "question": "Put the following in Order to make a Track followed by the Artist…",
      "items": [
        "CALL",
        "ME MA",
        "YBE C",
        "ARLY",
        "RAE J",
        "EPSEN"
      ],
      "answer": [
        "CALL",
        "ME MA",
        "YBE C",
        "ARLY",
        "RAE J",
        "EPSEN"
      ]
    },
    {
      "type": "letters",
      "question": "Name the Track from the opening lyrics…",
      "answer": "C",
      "display_answer": "Chelsea Dagger (The Fratellis)",
      "media": {
        "type": "video",
        "url": "media\\cd.mp4"
      }
    },
    {
      "type": "letters",
      "question": "One Hit Wonder: Name the Artist…",
      "answer": "C",
      "display_answer": "Cutting Crew (I Just Died in Your Arms Tonight)",
      "media": {
        "type": "video",
        "url": "media\\cc.mp4"
      }
    },
    {
      "type": "multiple_choice",
      "question": "For how many weeks did Bryan Adams’ “(Everything I Do) I Do It for You”, from Robin Hood: Prince of Thieves, stay at Number One in the UK?",
      "options": [
        "10 Weeks",
        "12 Weeks",
        "14 Weeks",
        "16 Weeks",
        "18 Weeks",
        "20 Weeks"
      ],
      "answer": "16 Weeks"
    },
    {
      "type": "multiple_choice",
      "question": "Name the Artist who sang the Original…",
      "options": [
        "Amy Whinehouse",
        "Mark Ronson",
        "The Kooks",
        "The Zutons",
        "The Coral",
        "The Wombats"
      ],
      "answer": "The Zutons",
      "media": {
        "type": "video",
        "url": "media\\tz.mp4"
      }
    },
    {
      "type": "numbers",
      "question": "In what year did Robbie Williams leave Take That?",
      "answer": 1995
    }
  ],
  "2026-07-17": [
    {
      "type": "wordsnake",
      "question": "Word Snake: Name the Artist…",
      "answer": "Chris Martin",
      "media": {
        "type": "video",
        "url": "media\\cm.mp4"
      }
    },
    {
      "type": "sequence",
      "question": "Put these six chart‑hit songs by Steps in order of their original release…",
      "items": [
        "5,6,7,8",
        "Last Thing on My Mind",
        "One for Sorrow",
        "Heartbeat / Tragedy",
        "Better Best Forgotten",
        "Love’s Got a Hold on My Heart"
      ],
      "answer": [
        "5,6,7,8",
        "Last Thing on My Mind",
        "One for Sorrow",
        "Heartbeat / Tragedy",
        "Better Best Forgotten",
        "Love’s Got a Hold on My Heart"
      ]
    },
    {
      "type": "letters",
      "question": "Name the Artist from the Album Cover…",
      "answer": "F",
      "display_answer": "Fleetwood Mac (Rumours)",
      "media": {
        "type": "image",
        "url": "media\\fm.png"
      }
    },
    {
      "type": "letters",
      "question": "Name the Track…",
      "answer": "O",
      "display_answer": "Otherside (Red Hot Chili Peppers)",
      "media": {
        "type": "audio",
        "url": "media\\os.mp3"
      }
    },
    {
      "type": "sequence",
      "question": "Put the following in Order to make a Track followed by the Artist…",
      "items": [
        "DIRE",
        "STRAI",
        "TS MO",
        "NEY F",
        "OR NO",
        "THING"
      ],
      "answer": [
        "DIRE",
        "STRAI",
        "TS MO",
        "NEY F",
        "OR NO",
        "THING"
      ]
    },
    {
      "type": "letters",
      "question": "Name the Track from the opening lyrics…",
      "answer": "T",
      "display_answer": "Take On Me (A-Ha)",
      "media": {
        "type": "video",
        "url": "media\\to.mp4"
      }
    },
    {
      "type": "letters",
      "question": "One Hit Wonder: Name the Artist…",
      "answer": "W",
      "display_answer": "Wamdue Project (King of My Castle)",
      "media": {
        "type": "video",
        "url": "media\\wp.mp4"
      }
    },
    {
      "type": "multiple_choice",
      "question": "What is the rapper 50 Cent’s real name?",
      "options": [
        "Nathan Nickelson",
        "Calvin Cordozar Broadus Jr.",
        "O’Shea Jackson",
        "Curtis Jackson",
        "Arthur Dollar",
        "Shawn Corey Carter"
      ],
      "answer": "Curtis Jackson"
    },
    {
      "type": "multiple_choice",
      "question": "Name the Artist who sang the Original…",
      "options": [
        "Wake Wake",
        "Walk Walk",
        "Talk Take",
        "Take Talk",
        "Talk Talk",
        "Take Take"
      ],
      "answer": "Talk Talk",
      "media": {
        "type": "video",
        "url": "media\\ml.mp4"
      }
    },
    {
      "type": "numbers",
      "question": "In what decade did Queen score their first UK Number One single?",
      "answer": 1970
    }
  ],
  "2026-07-16": [
    {
      "type": "wordsnake",
      "question": "Word Snake: Name the Artist…",
      "answer": "Bruno Mars",
      "media": {
        "type": "video",
        "url": "media\\bmare.mp4"
      }
    },
    {
      "type": "sequence",
      "question": "Put these six chart‑hit songs with the word “Dance” in the title in order of their original release…",
      "items": [
        "Dancing in the Street — Martha & The Vandellas",
        "Dancing Queen — ABBA",
        "Let’s Dance — David Bowie",
        "Dancing in the Street — Mick Jagger & David Bowie",
        "I Wanna Dance with Somebody — Whitney Houston",
        "Dance Monkey — Tones and I"
      ],
      "answer": [
        "Dancing in the Street — Martha & The Vandellas",
        "Dancing Queen — ABBA",
        "Let’s Dance — David Bowie",
        "Dancing in the Street — Mick Jagger & David Bowie",
        "I Wanna Dance with Somebody — Whitney Houston",
        "Dance Monkey — Tones and I"
      ]
    },
    {
      "type": "letters",
      "question": "Name the Artist from the Album Cover…",
      "answer": "T",
      "display_answer": "Taylor Swift (1989)",
      "media": {
        "type": "image",
        "url": "media\\tay.png"
      }
    },
    {
      "type": "letters",
      "question": "Name the Track…",
      "answer": "E",
      "display_answer": "Escape (Enrique Iglesias)",
      "media": {
        "type": "audio",
        "url": "media\\eee.mp3"
      }
    },
    {
      "type": "sequence",
      "question": "Put the following in Order to make a Track followed by the Artist…",
      "items": [
        "THE BE",
        "AUTIFU",
        "L SOUT",
        "H SONG",
        "FOR W",
        "HOEVER"
      ],
      "answer": [
        "THE BE",
        "AUTIFU",
        "L SOUT",
        "H SONG",
        "FOR W",
        "HOEVER"
      ]
    },
    {
      "type": "letters",
      "question": "Name the Track from the opening lyrics…",
      "answer": "G",
      "display_answer": "Gangsta's Paradise (Coolio)",
      "media": {
        "type": "video",
        "url": "media\\coolio.mp4"
      }
    },
    {
      "type": "letters",
      "question": "One Hit Wonder: Name the Artist…",
      "answer": "S",
      "display_answer": "Semisonic (Closing Time)",
      "media": {
        "type": "video",
        "url": "media\\ssct.mp4"
      }
    },
    {
      "type": "tapspot",
      "question": "Where is Gene Simmons?",
      "target": [
        {
          "x": 32.8,
          "y": 73.1
        },
        {
          "x": 30.1,
          "y": 75.8
        },
        {
          "x": 29.2,
          "y": 78.8
        },
        {
          "x": 29.1,
          "y": 81.1
        },
        {
          "x": 27.2,
          "y": 83.6
        },
        {
          "x": 24.9,
          "y": 87.6
        },
        {
          "x": 24.8,
          "y": 92.8
        },
        {
          "x": 26.2,
          "y": 94
        },
        {
          "x": 29.5,
          "y": 90.3
        },
        {
          "x": 32.6,
          "y": 86
        },
        {
          "x": 35.3,
          "y": 84.6
        },
        {
          "x": 35.5,
          "y": 78.9
        },
        {
          "x": 35.5,
          "y": 74.6
        }
      ],
      "media": {
        "type": "image",
        "url": "media\\rsars.png"
      }
    },
    {
      "type": "multiple_choice",
      "question": "Name the Artist who sang the Original…",
      "options": [
        "Simple Minds",
        "Spin Doctors",
        "Saw Doctors",
        "Duran Duran",
        "Tears for Fears",
        "Spandau Ballet"
      ],
      "answer": "Tears for Fears",
      "media": {
        "type": "video",
        "url": "media\\hstff.mp4"
      }
    },
    {
      "type": "numbers",
      "question": "What year did Celine Dion’s My Heart Will Go On reach Number One in the UK?",
      "answer": 1998
    }
  ]
};
