// SpeedQuiz — Monthly Questions
// Auto-generated by excel_to_questions.html
// Do not edit by hand — regenerate from your Excel template instead.
//
// Columns by type:
//   multiple_choice : options (up to 6), answer
//   letters         : answer (letter), display_answer (full word)
//   numbers         : answer (integer)
//   sequence        : items (up to 6, shown shuffled), answer (correct order array)
//   optional media  : column P is the file/URL; column Q can specify image, video, or audio.
//                     If Q is blank, the type is inferred from its extension.

window.QUIZ_QUESTIONS = {
  "2026-07-14": [
    {
      "type": "letters",
      "question": "Name the Artist from the Album Cover…",
      "answer": "W",
      "display_answer": "The White Stripes",
      "media": {
        "type": "image",
        "url": "media\\the-white-stripes-elephant.jpg"
      }
    },
    {
      "type": "sequence",
      "question": "Put these six chart‑hit songs by Madonna in order of their original release…",
      "items": [
        "Like a Virgin",
        "Holiday",
        "Material Girl",
        "Papa Don’t Preach",
        "Vogue",
        "Like a Prayer"
      ],
      "answer": [
        "Holiday",
        "Like a Virgin",
        "Material Girl",
        "Papa Don’t Preach",
        "Like a Prayer",
        "Vogue"
      ]
    },
    {
      "type": "letters",
      "question": "Name the Track…",
      "answer": "W",
      "display_answer": "Watching The Detectives (Elvis Costello)",
      "media": {
        "type": "audio",
        "url": "media\\WatchingTheDetectives.mp3"
      }
    },
    {
      "type": "letters",
      "question": "Name the Track from the opening lyrics…",
      "answer": "S",
      "display_answer": "Sympathy for the Devil (The Rolling Stones)",
      "media": {
        "type": "video",
        "url": "media\\TheRollingStones.mp4"
      }
    },
    {
      "type": "letters",
      "question": "One Hit Wonder: Name the Artist…",
      "answer": "B",
      "display_answer": "Baz Lurman (Everyone's Free to Wear Sunscreen)",
      "media": {
        "type": "video",
        "url": "media\\Baz Lurman.mp4"
      }
    },
    {
      "type": "numbers",
      "question": "In what year did Wham! reach Number One in the UK with Last Christmas",
      "answer": 2021
    },
    {
      "type": "sequence",
      "question": "Put the following in Order to make a Track followed by the Artist…",
      "items": [
        "ASI",
        "WAL",
        "WON",
        "DER",
        "S",
        "L O"
      ],
      "answer": [
        "WON",
        "DER",
        "WAL",
        "L O",
        "ASI",
        "S"
      ]
    },
    {
      "type": "letters",
      "question": "Name the Artist…",
      "answer": "S",
      "display_answer": "Shakira",
      "media": {
        "type": "video",
        "url": "media\\Shak.mp4"
      }
    },
    {
      "type": "sequence",
      "question": "Put these planets in order from the Sun (nearest first):",
      "items": [
        "Earth",
        "Mars",
        "Mercury",
        "Venus"
      ],
      "answer": [
        "Mercury",
        "Venus",
        "Earth",
        "Mars"
      ]
    },
    {
      "type": "multiple_choice",
      "question": "Which planet is closest to the Sun?",
      "options": [
        "Venus",
        "Earth",
        "Mars",
        "Mercury",
        "Jupiter",
        "Saturn"
      ],
      "answer": "Mercury"
    }
  ]
};
