// SpeedQuiz — Monthly Questions
// Auto-generated by excel_to_questions.html
// Do not edit by hand — regenerate from your Excel template instead.
//
// Columns by type:
//   multiple_choice : options (up to 6), answer
//   letters         : answer (letter), display_answer (full word)
//   letters_shuffled: same as letters, but the grid is randomly reordered
//   numbers         : answer (integer)
//   word            : answer (typed in full), optional accepted variants
//   sequence        : items (up to 6, shown shuffled), answer (correct order array)
//   assemble        : answer (auto-split into up to 6 shuffled pieces by the app)
//   multitap        : options (up to 6), answers (array — every correct one)
//   wordsnake       : answer (word or phrase, max 20 letters — spaces don't count)
//   tapspot         : target (JSON array of {x,y} points from the Shape Picker
//                     tool, min 3), requires an image in the media column
//   optional media  : column P is the file/URL; column Q can specify image, video, or audio.
//                     If Q is blank, the type is inferred from its extension.

window.QUIZ_QUESTIONS = {
  "2026-07-27": [
    {
      "type": "assemble",
      "question": "Yellow",
      "answer": "Coldplay Eat a Dick"
    }
  ]
};
